# Generated by Django 3.2.5 on 2021-07-23 05:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='application',
            name='creation_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='application',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.employee'),
        ),
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('R', 'Repair'), ('S', 'Service'), ('C', 'Consult')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('M', 'Manager'), ('D', 'Director'), ('T', 'Tech support')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('O', 'Opened'), ('W', 'In work'), ('C', 'Closed')], default='O', max_length=1),
        ),
    ]
