# Generated by Django 3.2.5 on 2021-07-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20210723_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('R', 'Repair'), ('S', 'Service'), ('C', 'Consult')], max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_nickname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('M', 'Manager'), ('D', 'Director'), ('T', 'Tech support')], max_length=1),
        ),
    ]
